spring:
  application:
    name: composebean

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/composebean?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

file:
  upload-dir: uploads/products

slack:
  bot-token: ${SLACK_BOT_TOKEN:}
  order-receiver-id: ${SLACK_ORDER_RECEIVER_ID:}
